set_property IOSTANDARD LVCMOS33 [get_ports {count[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[0]}]
set_property PACKAGE_PIN T10 [get_ports {count[3]}]
set_property PACKAGE_PIN T9 [get_ports {count[2]}]
set_property PACKAGE_PIN J5 [get_ports {count[1]}]
set_property PACKAGE_PIN H5 [get_ports {count[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {freq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {freq[0]}]
set_property PACKAGE_PIN A8 [get_ports {freq[0]}]
set_property PACKAGE_PIN C11 [get_ports {freq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { clk }]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports { clk }]
